title: IM.UR.CITY
description: "Revolutionizing the Way We Interact with Artificial Intelligence"
theme: just-the-docs

url: https://IM.UR.CITY

aux_links:
  "OUR COMMUNITY":
    - "https://twitter.com/ImUrCity"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

